version: 2.1

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

orbs:
  orb-tools: circleci/orb-tools@9.0.1
  dscar: moneyforward/dscar-rubocop@<< pipeline.parameters.dev-orb-version >>

anchors:
  dscar-default-executor: &dscar-default-executor
    name: dscar/default
    project-git_url: "" # << pipeline.project.git_url >>
    git-base_revision: "" # << pipeline.git.base_revision >>
    git-revision: "" # << pipeline.git.revision >>

jobs:
  integration-test-1:
    executor:
      <<: *dscar-default-executor
    steps:
      - checkout
      - dscar/analyze

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          context: dscar
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          context: dscar
          orb-name: moneyforward/dscar
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          context: dscar
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
    unless: << pipeline.parameters.run-integration-tests >>
  integration-tests:
    jobs:
      - integration-test-1
    when: << pipeline.parameters.run-integration-tests >>
